[tool.poetry]
name = "as"
version = "1"
description = ""
authors = ["Artyom"]

[tool.poetry.dependencies]
python = "^3.6"
pyqt5 = "^5.13"
pymongo = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
